### PR TITLE
Add missing index.js required for import syntax to work

### PR DESCRIPTION
**Pull request by dgaus**

### CODE REVIEW

**Comment by earthtone** [comment]
Hey @dgaus ! Thanks for the PR. Not sure if this is change is necessary for users trying to import the built files from the NPM package. Have you discovered an issue with trying to `import` the npm package in your project?

**Comment by dgaus** [comment]
Yes, otherwise we can't import it. Using webpacker on rails, so `import VueMarkdownLite from '@earthtone/vue-markdown-lite'` yields 

```
ERROR in ./app/javascript/components/...
Module not found: Error: Can't resolve '@earthtone/vue-markdown-lite'
```

The order it tries to resolve looks like this:
```
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite.vue]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite.mjs]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite.js]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite.sass]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite.scss]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite.css]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite.module.sass]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite.module.scss]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite.module.css]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite.png]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite.svg]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite.gif]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite.jpeg]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite.jpg]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/dist/vue-markdown-lite.esm.js]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/dist/vue-markdown-lite.esm.js.vue]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/dist/vue-markdown-lite.esm.js.mjs]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/dist/vue-markdown-lite.esm.js.js]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/dist/vue-markdown-lite.esm.js.sass]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/dist/vue-markdown-lite.esm.js.scss]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/dist/vue-markdown-lite.esm.js.css]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/dist/vue-markdown-lite.esm.js.module.sass]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/dist/vue-markdown-lite.esm.js.module.scss]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/dist/vue-markdown-lite.esm.js.module.css]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/dist/vue-markdown-lite.esm.js.png]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/dist/vue-markdown-lite.esm.js.svg]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/dist/vue-markdown-lite.esm.js.gif]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/dist/vue-markdown-lite.esm.js.jpeg]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/dist/vue-markdown-lite.esm.js.jpg]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/dist/vue-markdown-lite.umd.js]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/dist/vue-markdown-lite.umd.js.vue]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/dist/vue-markdown-lite.umd.js.mjs]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/dist/vue-markdown-lite.umd.js.js]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/dist/vue-markdown-lite.umd.js.sass]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/dist/vue-markdown-lite.umd.js.scss]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/dist/vue-markdown-lite.umd.js.css]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/dist/vue-markdown-lite.umd.js.module.sass]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/dist/vue-markdown-lite.umd.js.module.scss]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/dist/vue-markdown-lite.umd.js.module.css]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/dist/vue-markdown-lite.umd.js.png]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/dist/vue-markdown-lite.umd.js.svg]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/dist/vue-markdown-lite.umd.js.gif]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/dist/vue-markdown-lite.umd.js.jpeg]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/dist/vue-markdown-lite.umd.js.jpg]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/index]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/index.vue]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/index.mjs]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/index.js]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/index.sass]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/index.scss]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/index.css]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/index.module.sass]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/index.module.scss]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/index.module.css]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/index.png]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/index.svg]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/index.gif]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/index.jpeg]
[/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/index.jpg]
```
So there are other alternatives if you don't want to use index.js but it is the convention to define an entry point

**Comment by earthtone** [comment]
Sorry, this might be down to bad documentation on my part. The entry point is going to differ based on whether you are using the ESModules, CommonJS, Unpkg, or SFC build. I just realized the documentation in the README is completely wrong for SFCs. I'm using [this guide for reference](https://vuejs.org/v2/cookbook/packaging-sfc-for-npm.html#How-does-npm-know-which-version-to-serve-to-a-browser-build-process).

Does this issue occur when trying to register the component globally (i.e. using the module's `install`), or when you try to import the modules as an SFC inside another component?

If you need to grab the `SFC` it's hidden behind a namespace defined in the `package.json`'s browser property and can be imported using:

```js
import VueMarkdownLite form '@earthtone/vue-markdown-lite/sfc'
```

Sorry if this isn't your issue. Just trying to clarify why the generated entry points aren't working for you automatically.

**Comment by dgaus** [comment]
Thanks for the reply, I'm no expert in packaging myself. If I try to import from `/sfc` I get

`aliased from description file /home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/package.json with mapping './sfc' to 'src/vue-markdown-lite.vue'`

but it fails anyways as it is looking inside node_modules for the vue-markdown-lite project? 
`/home/diego/code/portal/node_modules/@earthtone/vue-markdown-lite/node_modules/src/vue-markdown-lite.vue doesn't exist`

I'm not sure what you mean by using the module's install, I'm just trying to import and use the component as described in https://github.com/earthtone/vue-markdown-lite#es-module

I realize I don't have a `dist` folder and that's why it's failing when trying to import it as `import VueMarkdownLite from '@earthtone/vue-markdown-lite'`.

Also there could be something wrong with my setup, but I have no other packages in node_modules that use this sfc syntax so I don't know how to check. Loading .vue files locally does work, though.

Do you have a dist folder locally? Perhaps committing the umd/esm/min.js files would also work instead of having index.js

**Comment by earthtone** [comment]
Hmm. If there is no `/dist` directory in the `node_modules` sub directory that's a massive mistake on my part. I'll devote some time this weekend to double checking that the npm package is in fact what it _should be_ and that the documentation is accurate and up-to-date. 

Otherwise, I'm inclined to merge your PR if it will fix things for your use case and doesn't negatively impact any other implementation. I think merging the one `index.js` file is a far simpler solution than having to worry about `package.json` trickery with name spaces or anything like that.

**Comment by dgaus** [comment]
Looking at other packages we're using I think just including the dist/ folder should make it work, as some of them don't have an index.js and just go into the "main" entrypoint in package.json. But whatever you think is best, thanks for taking the time!

**Comment by earthtone** [comment]
Hey @dgaus , I've just created a release branch that should automate builds and deployments moving forward. There's a new version of the package up on NPM now that includes the built files in `/dist`. If you can update the version in your project and let me know that this fixes your issue, I'd really appreciate that.

Sorry for the complete failure on my part to actually _ship_ the package, but thanks so much for your patience and your help.

**Comment by dgaus** [comment]
Cool, works now without index.js, no worries at all, thanks for your work!

**Pull request closed without merging**
